language: python
cache: pip
python:
  - "3.6"
  - "3.6.1"
  - "3.6.2"

before_install:
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
script: python setup.py test

after_success:
  - codecov
