language: python
cache: pip
python:
  - "3.6"
  - "3.6.1"
  - "3.6.2"

before_install:
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
install:
  - pip install .
script: pytest --cov=lyskel

after_success:
  - codecov
