language: python
cache: pip
dist: xenial
sudo: required
python:
  - "3.6"
  - "3.6.6"
  - "3.6.7"
  - "3.7-dev"

#matrix:
#  allow_failures:
#    - python: "3.7"

addons:
  apt:
    packages:
      - lilypond

before_install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
  - pipenv install
  - pip install codecov
  - pip install -e .

script: pytest

after_success:
  - codecov
