language: python
cache: pip
python:
  - "3.6"
  - "3.6.1"
  - "3.6.2"
  - "3.6.3"
  - "3.6.4"
  - "3.6.5"
  - "3.7-dev"

#matrix:
#  allow_failures:
#    - python: "3.7"

addons:
  apt:
    packages:
      - lilypond

before_install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
  - pipenv install
  - pip install codecov
  - pip install -e .

script: pytest

after_success:
  - codecov
