language: python
cache: pip
python:
  - "3.6"
  - "3.6.1"
  - "3.6.2"

before_install:
  - pip install codecov
  - pip install pytest
  - pip install pytest-cov
  - pip install -e .
  - sudo apt-get -qq update
  - sudo apt-get install lilypond
script: python setup.py test

after_success:
  - codecov
